//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kentico.Xperience.Dynamics365.Sales.Controls
{


    public partial class Mapping
    {

        /// <summary>
        /// MessageControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl MessageControl;

        /// <summary>
        /// ContainerControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl ContainerControl;

        /// <summary>
        /// ContactFirstName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Base.Web.UI.CMSDropDownList ContactFirstName;

        /// <summary>
        /// ContactMiddleName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Base.Web.UI.CMSDropDownList ContactMiddleName;

        /// <summary>
        /// ContactLastName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Base.Web.UI.CMSDropDownList ContactLastName;

        /// <summary>
        /// ContactEmail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Base.Web.UI.CMSDropDownList ContactEmail;

        /// <summary>
        /// ContactMobilePhone control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Base.Web.UI.CMSDropDownList ContactMobilePhone;

        /// <summary>
        /// ContactBusinessPhone control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Base.Web.UI.CMSDropDownList ContactBusinessPhone;

        /// <summary>
        /// ContactJobTitle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Base.Web.UI.CMSDropDownList ContactJobTitle;

        /// <summary>
        /// ContactAddress1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Base.Web.UI.CMSDropDownList ContactAddress1;

        /// <summary>
        /// ContactCity control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Base.Web.UI.CMSDropDownList ContactCity;

        /// <summary>
        /// ContactZIP control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Base.Web.UI.CMSDropDownList ContactZIP;
    }
}
